### ISSUE TITLE
Knex does not build with webpack

### ISSUE THREAD

**Issue by tjwebb** [tgriesser/knex#1518]
Because of https://github.com/tgriesser/knex/pull/1427. The entrypoint require needs to be fixed. All webpack users have to downgrade to knex 0.11.3 until this is fixed.

**Comment by elhigu** [comment]
Its not about fixing the entrypoint, webpack build is already functional. 

There seem to be bunch of syntax errors in code in index.html. 

Also one example code, which throws an exception (which is actually correct functionality) leaks an exception. 

Failing code in page is:

```js
knex('accounts')
    .where('login', undefined)
    .select()
    .toSQL();
    //Undefined binding(s) detected when compiling SELECT query: select * from "accounts" where "login" = ?
```

We need to add try-catch to prevent exception from leaking + fix the syntax / lodash errors. We also try to add some automatic test which checks that index.html is loading without errors.

**Comment by elhigu** [comment]
![knex_js_-_a_sql_query_builder_for_javascript](https://cloud.githubusercontent.com/assets/696345/16185990/6b4feb6a-36d0-11e6-9dc6-1d6955f22331.jpg)

**Comment by tgriesser** [comment]
Yeah, I think we should actually revert that change in #1427 and deprecate the version being exposed on the knex object. If anyone wants to know the package version they can just `require('knex/package.json').version` themselves.

**Comment by elhigu** [comment]
@tgriesser that is already reverted while ago https://github.com/tgriesser/knex/commit/2fd63a7868a4d5f229d37cdd20f5816c9f442b7a

**Comment by tgriesser** [comment]
Right but I'm saying that now if you're building with webpack either you now either need to:

1. add a rule for .json and json-loader and the entire `package.json` file gets added to the build
2. add a rule for .json and add empty-loader 

I'm saying that we could deprecate `knex.VERSION` / `knex.__knex__` and just say that if you want to know the version number in node, just do `require('knex/package').version` as you would in other modules.

**Comment by reggi** [comment]
This is giving me problems :/ 

http://stackoverflow.com/questions/37953848/knex-webpack-cannot-find-module-package-json

**Comment by tgriesser** [comment]
Should be fixed in the latest

**Comment by teckays** [comment]
I have `"knex@0.12.6"` installed and I still get this:
`Error: Undefined binding(s) detected when compiling SELECT query: select "table".* from "table" where "id" = ? and "column" = ? limit ?`
Notice `limit ?` is appended and expects a value which I do not intend to pass.
