### ISSUE TITLE
Error when trying to rollback a migration

### ISSUE THREAD

**Issue by dnlgrwd87** [tgriesser/knex#3401]
# Environment

Knex version: 0.19.2
Database + version: PostgreSQL 11
OS: macOS Mojave 10.14.6

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Following the steps excatly provided in http://perkframework.com/v1/guides/database-migrations-knex.html I successfully create and run a migration. However, when trying to `knex migrate:rollback`, I get an error unless I prefix the command with `npx`.

2. Error message
```
.spread((batchNo, log) => {
         ^

TypeError: initKnex(...).migrate.rollback(...).spread is not a function
```

**Comment by JordoHeffernan** [comment]
I am running into this issue but am using yarn for package management on this particular project and when I try to prefix the comman with `npx` I get an error that says: 
`/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:252
      throw unsupportedURLType(urlparse.protocol, res.rawSpec)
      ^

Error: Unsupported URL Type "knex:": knex:migrate
`

Why was this closed with no comments or support provided? I haven't been able to rollback in months.

**Comment by ricardograca** [comment]
@JordoHeffernan You're issue is completely different and seems to be a misunderstanding of how knex works. You're better off just posting a question on StackOverflow about a usage question.

**Comment by JordoHeffernan** [comment]
@ricardograca thank you for replying. The error above was what came up when I attempted to run `npx knex migrate:rollback` assuming full well it wouldn't work but just as an attempt because of the original poster's message. 

However, any attempt to run `knex migrate:rollback` fails with the following error:
`/usr/local/lib/node_modules/knex/bin/cli.js:212
        .spread((batchNo, log) => {
         ^   
TypeError: initKnex(...).migrate.rollback(...).spread is not a function
    at Command.commander.command.description.option.action (/usr/local/lib/node_modules/knex/bin/cli.js:212:10)
    at Command.listener (/usr/local/lib/node_modules/knex/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/usr/local/lib/node_modules/knex/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/knex/node_modules/commander/index.js:474:21)
    at Liftoff.invoke (/usr/local/lib/node_modules/knex/bin/cli.js:280:13)
    at Liftoff.execute (/usr/local/lib/node_modules/knex/node_modules/liftoff/index.js:201:12)
    at module.exports (/usr/local/lib/node_modules/knex/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/knex/node_modules/liftoff/index.js:191:5)
    at /usr/local/lib/node_modules/knex/node_modules/liftoff/index.js:149:9
    at /usr/local/lib/node_modules/knex/node_modules/v8flags/index.js:138:14
    at /usr/local/lib/node_modules/knex/node_modules/v8flags/index.js:41:14
    at /usr/local/lib/node_modules/knex/node_modules/v8flags/index.js:53:7
    at process._tickCallback (internal/process/next_tick.js:61:11)'

I can open a question on StackOverflow but none of the other threads regarding this issue seem to have any solutions from what I've found.

**Comment by ricardograca** [comment]
Ah wait, `.spread()` was from Bluebird, and it was removed. What version of knex are you using? I'm almost certain this was fixed in one of the latest versions.

**Comment by JordoHeffernan** [comment]
Both locally for that project and globally I tried installing the most recent version (0.19.4) and am still getting the issue.

**Comment by angela-mylo** [comment]
I was getting the same error, but was able to resolve it by upgrading my global reference of knex to the latest version:
`npm install -g knex`

**Comment by JordoHeffernan** [comment]
Thank you for the reply @angela-mylo ! Unfortunately no such luck for me.

**Comment by istvanp** [comment]
@JordoHeffernan what do you get when you do:
```
knex --version
```
I had this before doing a global install as @angela-mylo suggested:
```
Knex CLI version:  0.14.6
Local Knex version:  0.19.4
```
After running `npm install -g knex`:
```
Knex CLI version: 0.19.4
Knex Local version: 0.19.4
```
And the rollback command ran properly.

**Comment by JordoHeffernan** [comment]
@istvanp Thanks for the reply!

When I run `knex --version` I get the following, this is after running `npm install -g knex`
`  Knex CLI version:   
    Local Knex version:   `

I get the same results in both my project folder and root directory.

**Comment by hades2510** [comment]
You may try running `npx knex migrate:rollback`. This should run the latest version of knex CLI.

**Comment by JordoHeffernan** [comment]
@hades2510 That worked. Thank you! I thought I had tried that before to no avail but it worked this time. Always a possibility of user error when typing the command, either way, thank you so much!
